### ISSUE TITLE
Can't open input file ./unpack.sh: line 21: cd: BIOS_Inspiron.exe_decompressed.hdr.extracted: No such file or directory #####################

### ISSUE THREAD

**Issue by wheelloader** [T-vK/DellBiosUnpackerPOC#1]
Hi,
I want to extract my vbios Dell Laptop 7567. I tried using DellBiosUnpacker and come with error even using your XPS Bios file. Please see below

`
fariz@fariz-Inspiron-15-7000-Gaming:~/Documents/DellBiosUnpackerPOC-master$ sudo ./unpack.sh BIOS_Inspiron.exe
[sudo] password for fariz: 
Building native extensions. This could take a while...
Successfully installed zlib-2.1.1
Parsing documentation for zlib-2.1.1
Done installing documentation for zlib after 0 seconds
Successfully installed hex_string-1.0.1
Parsing documentation for hex_string-1.0.1
Done installing documentation for hex_string after 0 seconds
2 gems installed
Decompressed data written to BIOS_Inspiron.exe_decompressed.hdr
Cloning into 'PFSExtractor'...
remote: Enumerating objects: 11, done.
remote: Total 11 (delta 0), reused 0 (delta 0), pack-reused 11
Receiving objects: 100% (11/11), 5.34 KiB | 5.34 MiB/s, done.
Resolving deltas: 100% (2/2), done.
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fariz/Documents/DellBiosUnpackerPOC-master/PFSExtractor
Scanning dependencies of target PFSExtractor
[ 50%] Building CXX object CMakeFiles/PFSExtractor.dir/pfsextractor.cpp.o
/home/fariz/Documents/DellBiosUnpackerPOC-master/PFSExtractor/pfsextractor.cpp: In function ‘uint8_t pfs_extract(const void*, size_t, const char*)’:
/home/fariz/Documents/DellBiosUnpackerPOC-master/PFSExtractor/pfsextractor.cpp:158:43: warning: format ‘%llX’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  158 |     printf("PFS %s Header:\nSignature: %llX\nVersion:   %X\nDataSize:  %X\n\n",
      |                                        ~~~^
      |                                           |
      |                                           long long unsigned int
      |                                        %lX
  159 |         isSubsection ? "Subsection File" : "File",
  160 |         fileHeader->Signature,
      |         ~~~~~~~~~~~~~~~~~~~~~              
      |                     |
      |                     long unsigned int
/home/fariz/Documents/DellBiosUnpackerPOC-master/PFSExtractor/pfsextractor.cpp:184:43: warning: format ‘%llX’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  184 |     printf("PFS %s Footer:\nSignature: %llX\nChecksum:  %X\nDataSize:  %X\n\n",
      |                                        ~~~^
      |                                           |
      |                                           long long unsigned int
      |                                        %lX
  185 |         isSubsection ? "Subsection File" : "File",
  186 |         fileFooter->Signature,
      |         ~~~~~~~~~~~~~~~~~~~~~              
      |                     |
      |                     long unsigned int
[100%] Linking CXX executable PFSExtractor
[100%] Built target PFSExtractor
Can't open input file
./unpack.sh: line 21: cd: BIOS_Inspiron.exe_decompressed.hdr.extracted: No such file or directory
#####################
#####################
#####################
Please adjust the path to your VBiosFinder installation otherwise the following will fail:
#####################
#####################
#####################
./unpack.sh: line 34: cd: /home/fedora/Projects/misc/VBiosFinder: No such file or directory
./unpack.sh: line 35: ./vbiosfinder: No such file or directory
fariz@fariz-Inspiron-15-7000-Gaming:~/Documents/DellBiosUnpackerPOC-master$ ^C
fariz@fariz-Inspiron-15-7000-Gaming:~/Documents/DellBiosUnpackerPOC-master$ 

`
I dont know what's wrong. I use Ubuntu 21.10. It look it's fail to decompress hdr extracted file. even it's  succes built hdr file.
I hope you can help with my issue.

Thank you.

**Comment by T-vK** [comment]
Sorry, it was a path issue in `unpack.sh`. Should be fixed now. If not, feel free to reopen.

**Comment by Gak-den** [comment]
Not sure if this is still maintained, so I'd like to chime in to let you know that I'm experiencing this same issue with my DELL laptop.
Which path should I edit to unpack.sh?

> ❯ ./unpack.sh G3_3579_3779_1.25.0.exe
<internal:/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require': cannot load such file -- hex_string (LoadError)
	from <internal:/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
	from ./hdr-unpack.rb:10:in '<main>'
fatal: destination path 'PFSExtractor' already exists and is not an empty directory.
CMake Warning (dev) at CMakeLists.txt:1 (PROJECT):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/Asterion/builds/3rdparty/DellBiosUnpackerPOC/PFSExtractor
[100%] Built target PFSExtractor
Can't open input file
./unpack.sh: line 22: cd: G3_3579_3779_1.25.0.exe_decompressed.hdr.extracted: No such file or directory
#####################
#####################
#####################
Please adjust the path to your VBiosFinder installation otherwise the following will fail:
#####################
#####################
#####################
/usr/lib/ruby/3.4.0/readline.rb:4: warning: reline was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add reline to your Gemfile or gemspec to silence this warning.
/home/Asterion/builds/3rdparty/VBiosFinder/src/cli.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
output will be stored in '/home/Asterion/builds/3rdparty/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes
Cleaning up garbage
/usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'File#initialize': No such file or directory @ rb_sysopen - /home/Asterion/builds/3rdparty/DellBiosUnpackerPOC/*.payload (Errno::ENOENT)
	from /usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'IO.open'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'FileUtils::Entry_#copy_file'
	from /usr/lib/ruby/3.4.0/fileutils.rb:1079:in 'FileUtils.copy_file'
	from /usr/lib/ruby/3.4.0/fileutils.rb:878:in 'block in FileUtils.cp'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2471:in 'block in FileUtils.fu_each_src_dest'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2485:in 'FileUtils.fu_each_src_dest0'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2469:in 'FileUtils.fu_each_src_dest'
	from /usr/lib/ruby/3.4.0/fileutils.rb:877:in 'FileUtils.cp'
	from /home/Asterion/builds/3rdparty/VBiosFinder/src/cli.rb:34:in 'VBiosFinder::CLI#extract'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'Thor::Command#run'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'Thor::Invocation#invoke_command'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor.rb:387:in 'Thor.dispatch'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in 'Thor::Base::ClassMethods#start'
	from _init.rb:7:in '<main>'

**Comment by Gak-den** [comment]
Side note, but any help would be very much appreciatedーVirt-manager outputs a message indicating that "Parameter 'x-pci-device-id' expects uint64"... I assume that my card cannot reliably be reset after booting/shutting down the VM, but there seems to be something else going on.

My system often freezes during the booting process into the host OS, and when I manage to reach a point where everything is loaded, sometimes the vfio_pci drivers may not fully bind the card to the VM and would still result in a lock up.
In both my host and guest OS, the card is detected as a generic 3D controller, though the vendor NVIDIA still shows up, and Device Manager shows "PCI\VEN_10DE&DEV_1C8C&SUBSYS_00000000&REV_A1", so I'm not sure if extracting a vBIOS would solve every problem.

    ❯ sudo dmesg | grep -i vfio
    [ 2.553048] VFIO - User Level meta-driver version: 0.3
    [ 2.695107] vfio_pci: add [10de:1c8c[ffffffff:ffffffff]] class 0x000000/00000000
    [ 4.222502] vfio_pci: add [10de:0fb9[ffffffff:ffffffff]] class 0x000000/00000000
    [ 216.060161] vfio-pci 0000:01:00.0: not ready 1023ms after resume; waiting
    [ 217.147997] vfio-pci 0000:01:00.0: not ready 2047ms after resume; waiting
    [ 219.260149] vfio-pci 0000:01:00.0: not ready 4095ms after resume; waiting
    [ 223.804082] vfio-pci 0000:01:00.0: not ready 8191ms after resume; waiting
    [ 232.508027] vfio-pci 0000:01:00.0: not ready 16383ms after resume; waiting
    [ 249.403758] vfio-pci 0000:01:00.0: not ready 32767ms after resume; waiting
    [ 283.707594] vfio-pci 0000:01:00.0: not ready 65535ms after resume; giving up

When I set these lines in the XML definition:

> <domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
     ...
     <devices>
         ...  
       <hostdev mode="subsystem" type="pci" managed="yes">
         <source>
           <address domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
         </source>
         <rom bar="on"/>
         <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0" multifunction="on"/>
       </hostdev>
         ...
     </devices>
         ...
     <qemu:override>
       <qemu:device alias="hostdev1">
         <qemu:frontend>
           <qemu:property name="romfile" type="string" value="~/GeForce_GTX_1050Ti_86-07-63-00-63.rom"/>
           <qemu:property name="x-pci-vendor-id" type="string" value="0x10de"/>
           <qemu:property name="x-pci-device-id" type="string" value="0x1c8c"/>
           <qemu:property name="x-pci-sub-vendor-id" type="string" value="0x1028"/>
           <qemu:property name="x-pci-sub-device-id" type="string" value="0x0870"/>
         </qemu:frontend>
       </qemu:device>
     </qemu:override>
   </domain>

Virt-manager either gives the aforementioned expected x-pci-device-id error, or...:

    Error starting domain: internal error: Unknown PCI header type '127' for device '0000:01:00:0'

I think I've read somewhere in the Arch wiki that the kernel itself may cause some issues with vfio_pci, probably a mix of factors with my particular laptop.
This particular error has also been reported on AMD platforms.
The current vBIOS I am using is one that I dumped directly from my dGPU. I've also tried patching it on the edk2, which didn't make the dGPU show up as anything else than a 3D controller in the guest OS.

> <domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
     <os>
       <type arch="x86_64" machine="pc-q35-10.0">hvm</type>
       <loader readonly="yes" type="pflash" format="raw">/home/Asterion/builds/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd</loader>
       <nvram format="raw">/var/lib/libvirt/qemu/nvram/win11_VARS.fd</nvram>
       <boot dev="hd"/>
       <bootmenu enable="yes"/>
     </os>
   </domain>


What I DIDN'T try:
---> Install proprietary NVIDIA drivers in my Linux host

**Comment by T-vK** [comment]
Try this: `gem install zlib hex_string`

**Comment by Gak-den** [comment]
Still no vBIOS.
Here is the [output](https://0x0.st/KdfX.txt).
The three payload files shown at the end have been generated in a directory.
