### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Th3Guardian** [T-vK/DellBiosUnpackerPOC#2]
Could you please unpack/extract from this one?

https://dl.dell.com/FOLDER07981163M/1/XPS_9570_1.23.0.exe

And this one as well if you don't mind. https://dl.dell.com/FOLDER06224897M/1/XPS_9570_1.16.2.exe

Thank you man!

I wonder how flashing it will work... since, obv can't read from bios (when extracting with GPUz for example) Do you think flashing will be the same or will it work? Like, can I flash it if even "reading" doesn't work from the board? Are there any peculiarities associated with this, since the rom is situated in the main bios, do you think a normal flash with nvflash will work?

I have an XPS 9570 with a 1050 Ti Max Q and I want to flash or edit the current bios to remove the TDP blocks or flash to a full laptop 1050 Ti.

I have an XPS 9570, thank you man!

For any help,

Really,

Thanks,

Kind regards,

David

**Comment by T-vK** [comment]
I wouldn't be comfortable sharing the extracted files for legal reasons, so if I extracted them, that wouldn't help you. But feel free to run the extractor script yourself. It should work just fine.
I have no clue how you would flash the extracted BIOS afterwards though... other than by buying an SPI flasher with the appropriate clamp for your chip and then use the appropriate cli tool to flash the file.
Or you could buy the chip on ebay and ask the seller to flash it with your BIOS first, then replace the chip on your motherboard using a reflow station or soldering iron.

**Comment by Th3Guardian** [comment]
Thing is I'm on Windows man, lol.

**Comment by T-vK** [comment]
There's [WSL 2](https://en.m.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by Th3Guardian** [comment]
Ok, but could you for example upload it somewhere like google drive real quick and I’d download it and you’d just remove it real quick after I’m done?

**Comment by Th3Guardian** [comment]
Hey,

How do I
