### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Th3Guardian** [T-vK/DellBiosUnpackerPOC#3]
How do I get this thing running?

Got bash, wsl.

**Comment by T-vK** [comment]
Make sure you have the following commands available in wsl: `bash, git, python2`. If you haven't find out which packages you need to install in order to get them.

The you need to run the following comnands with wsl:
```
git clone https://github.com/T-vK/DellBiosUnpackerPOC.git cd DellBiosUnpackerPOC
./hdr-unpack.py /path/to/my-bios-update-exe
```

And make sure you replace the `/path/to/my-bios-update-exe` with the correct one. It's probably something like `/mnt/c/XPS.......exe` if your file is at `C:\XPS.......exe`.

**Comment by Th3Guardian** [comment]
Thanks dude, workin on it now, how do I copy a message though in the command window? Right click seems to do the job but it runs the command immediately and doesn't let me edit,

**Comment by Th3Guardian** [comment]
for the first command it says fatal permission denied (for the git clone)

**Comment by T-vK** [comment]
Does that help?
https://stackoverflow.com/questions/51522912/git-clone-on-wsl-gives-permission-denied-error-wsl1

If not whats the output of `ls -la` and `pwd`?

**Comment by Th3Guardian** [comment]
Working on it bro, reinstalling right now as there could be issues with the install, but the install right now is taking some time.... o.O btw thanks for helping dude.... :)

**Comment by Th3Guardian** [comment]
Okay, I'm back online, shall I update first with sudo apt update and then install the necessary packs with sudo apt bash, git, python 2etc?

Dang still says permission denied on ./hdr-unpack.py /path/to/ . . . .

**Comment by T-vK** [comment]
Okay, so the git clone worked this time?
In that case, what is the output of `ls -la ./hdr-unpack.py`?
We might just have to make it executable if it isn't yet by running `chmod +x ./hdr-unpack.py`.

**Comment by Th3Guardian** [comment]
-rw-r--r-- 1 theguardian theguardian 1624 Feb 21 23:31 ./hdr-unpack.py

**Comment by T-vK** [comment]
Okay it's not executable, you need the run the chmod command then.

**Comment by Th3Guardian** [comment]
chmod +x ./hdr-unpack.py  /path/to/ . . . . ?

**Comment by Th3Guardian** [comment]
![image](https://user-images.githubusercontent.com/99751452/155030912-f264f81a-d95b-4ed0-ba12-7d3975622ba1.png)

**Comment by T-vK** [comment]
No, just `chmod +x ./hdr-unpack.py `
If it still doesnt work then, try running it like this instead:
`python2 ./hdr-unpack.py /path/to....`
 

Edit:

Just saw the screenshot. Seems like you have to explicitly run it using the python2 command from above.

**Comment by Th3Guardian** [comment]
Decompressed data written to /mnt/c/Utils/1.23.0.exe_decompressed.hdr

**Comment by T-vK** [comment]
Great, I guess you're done then, right? Unless you actually want to extraxt the GPU vBIOS from the BIOS file.
Make sure to backup your original BIOS first before flashing.

**Comment by Th3Guardian** [comment]
Wait, but... what's an hdr file, is that it? Yeah I want to extract the gpu vbios man. :D

**Comment by T-vK** [comment]
I'm not 100% sure. But that file contains all sorts of files that belong to the BIOS if you extract it. 
You can extract it further if you want. For that, you will need install the packages providing `make` and `cmake`.

**Comment by Th3Guardian** [comment]
Yeah, I did that, how would I carry on from there? Like UefiExtract and Vbiosfinder for example, are they already incorporated in your thing, or do I need to install them too somehow? How do I do that btw if they ain't packages, do I just place them at \\\wsl$\ or something?

**Comment by T-vK** [comment]
If you have installed make and cmake you can install PFSExtractor:

```
git clone https://github.com/LongSoft/PFSExtractor.git
cd PFSExtractor
cmake ./
make
cd ..
```

And then use it like this:
```
./PFSExtractor/PFSExtractor "1.23.0.exe_decompressed.hdr"
```

There will then be a directory called something like "1.23.0.exe_decompressed.hdr.extracted". It contains the extracted files.

You could then set up UefiExtract and Vbiosfinder if you wanted to extract the vbios. I found the vBios in the .payload file.

**Comment by Th3Guardian** [comment]
theguardian@DESKTOP-IETKG8L:~$ ./PFSExtractor/PFSExtractor "1.23.0.exe_decompressed.hdr"
Can't open input file

**Comment by Th3Guardian** [comment]
Hey dude, I just wanted to say thanks, and sorry if I'm a bit like arrogant or something, lol, I don't know even if I am, anyway, I was able to get the payload file, used a windows PFSExtractor, then used UEFIExtract to get a dump of all the bin files, but how do I get the rom file from these? ... like I have no idea, lol, how to use vbiosfinder etc.....

**Comment by Th3Guardian** [comment]
Hey dude, I just wanted to say sorry man, because for being maybe a bit arrogant and so on, but maybe I'm not lol, I don't know, anyway.. I was able to get the payload file, and used UEFIExtract to get a dump of all the bin files, but how do I find the rom file from these? I'm totally clueless man.. don't know at all lol, with vbiosfinderetc..........

Could you help me with that?

**Comment by T-vK** [comment]
If you dump the rom from the chip, you get a 32MB file. The file type if inspected with the `file` command is `Intel serial flash for PCH ROM`. 

```
file ./dump.rom
./dump.rom: Intel serial flash for PCH ROM
```

I couldn't find a file matching the size or the type in the extracted hdr file and the hdr file itself doesn't match either.

I'm not sure what to make out of this. Maybe there is another program required that bundles the extracted files together in a certain manner.

I have two suggestions for you:

- Ask the folks over at https://www.bios-mods.com/forum They have always been very helpful to me when it comes to modding and flashing BIOSes, although I haven't modded a Dell BIOS before.

- There are sellers on ebay that sell BIOS chips with any firmware you like. You could either buy a chip with the desired BIOS version and dump it yourself if you have the required hardware or you could nicely ask the seller if he can just send you the file directly without the chip. This seller has been very helpful to me in that regard: https://www.ebay.com/usr/bios-master specifically when it comes to Dell notebooks. I think I paid around 10 bucks for the file, which is a lot considering that there probably is a way to create it for free, but in case you can't figure it out, you might wanna consider it.

**Comment by Th3Guardian** [comment]
Wait, r u telling me that U don't know how to get the nvrom from the bin files? I haven't exactly slept much so I might not make much sense but, ur telling me that there is no way to get the rom from the 1.23 exe because there's something wrong with it or somethings different with it this time? Anway thanks man, I mean I haven't gotten to the vbiosfinder extract part yet, like I haven't been able to use it, but ur telling me u already did and u weren't able to get any further or smth, am i understanding u correctly?

I have the payload files and I was able to extract the bin files out of it but next step would be to use vbiosfinder (and perhaps UEFIExtract again though somehow?) but I don't know how, anyway thanks man and ur help is really appreciated!

Love u bro!

**Comment by T-vK** [comment]
If you're looking for the vBIOS files that's not a big problem. Those can be extracted using vbiosfinder from the .payload file, but my understanding was that you want the whole BIOS rom that would be flashed onto the SPI chip and that turns out to be more complicated.

**Comment by Th3Guardian** [comment]
Oh, no bro, just the vbios rom, could you help me out with that? I'm having a bit of a hard time setting up this thing, I'm unsure how to proceed with vbiosfinder (and uefiextract/rom-parser whatever **more** is needed for the procedure to work) as they don't have separate packages that you can just install with sudo apt install package.

**Comment by T-vK** [comment]
Okay, I totally misunderstood you then. 
In that case you need to set up vbiosfinder now.

To install vbiosfinder make sure you have the following installed: "git" "wget" "curl" "unzip" "ruby" "gem" "bundle" "7za" "make" "innoextract" "upx"

Then run:

```
git clone https://github.com/coderobe/VBiosFinder.git
cd VBiosFinder
wget https://github.com/LongSoft/UEFITool/releases/download/A58/UEFIExtract_NE_A58_linux_x86_64.zip -O ./UEFIExtract.zip
unzip ./UEFIExtract.zip -d ./3rdparty/
rm -f ./UEFIExtract.zip

git clone https://github.com/awilliam/rom-parser.git
cd rom-parser

bundle install --path=vendor/bundle
gem install bundler:1.17.3

make
mv ./rom-fixer ../3rdparty/
mv ./rom-parser ../3rdparty/
cd ..

bundle install --path=vendor/bundle
```

Now you can use vbiosfinder:

```
./vbiosfinder extract /path/to/section_0_1.23.0.payload
```

**Comment by Th3Guardian** [comment]
Hmm, it says

![image](https://user-images.githubusercontent.com/99751452/155224479-67c61e1d-27df-4d2b-930b-1d1761063391.png)

**Comment by T-vK** [comment]
Can you run `ls -la ./VBiosFinder/`? It seems like you already have it cloned and can probably skip that step.

**Comment by Th3Guardian** [comment]
Hmm says cannot access, don't have such a file or directory

**Comment by T-vK** [comment]
And if you simply run `ls -la` ?

**Comment by Th3Guardian** [comment]
![image](https://user-images.githubusercontent.com/99751452/155225294-81c41195-0f45-47be-8137-40f02767d2a6.png)

I was able to clone or get into it before actually, but I was in the mnt/c/Utils (blue line) folder, and I thought it was bad, and thought I needed to maybe might be in the home or whatever ~ folder, and do it from there, lol.. so I like changed directory and then did the git thing again then it started giving me those, lol

**Comment by Th3Guardian** [comment]
![image](https://user-images.githubusercontent.com/99751452/155225628-b173536f-014b-4e59-bdf6-cfceabc8be06.png)

**Comment by T-vK** [comment]
Can you need to run `cd theguardian` because the directory you're currently in is owned by `root`.
Then you can continue with the git clone command etc.

**Comment by Th3Guardian** [comment]
okay im back on track bro

**Comment by Th3Guardian** [comment]
![image](https://user-images.githubusercontent.com/99751452/155225794-fc197e3f-b0d2-450b-a5d4-f4d2d03d5b6b.png)
thanks man

**Comment by Th3Guardian** [comment]
![image](https://user-images.githubusercontent.com/99751452/155226125-b4c9a866-5c63-4097-a4c3-050904bfa1ac.png)

**Comment by Th3Guardian** [comment]
yoo, it works

**Comment by Th3Guardian** [comment]
dude, !!! thanks man, look! lol

![image](https://user-images.githubusercontent.com/99751452/155226709-07fcedc8-ec34-47f5-8ea4-5233eb10941f.png)

yoo, thanks man, love u lol, heh :) couldnt have done it with out u lol

**Comment by T-vK** [comment]
Great, glad to hear that you finally got what you need. :)

**Comment by Th3Guardian** [comment]
Dude, ur amazing,! and awesome, heh :)

**Comment by Th3Guardian** [comment]
I wonder if I can flash with nvflash, if sensing/reading the bios won't even work, do you think a "write" would? If I force it with nvflash, and maybe I use the same rom file, just in case, to be sure, as it's basically what's sitting on the chip right now, what do u think, nothing could go wrong right? ....

**Comment by Th3Guardian** [comment]
Wait but, where would I find the files?

**Comment by Th3Guardian** [comment]
(nvm got it) the files

**Comment by T-vK** [comment]
I think nvflash is not gonna help you on a notebook.

My understanding is that desktop graphics cards have their own flash chip holding their firmware (aka vBios). 
On notebooks, the GPU firmware can't be flashed permanently because the GPU doesn't have a dedicated chip for that. So what manufactures are doing is they store the firmwares (vBIOS roms) in the BIOS, on the same chip and then every time you boot the computer, it loads the firmwares it finds in the BIOS onto the GPU (which only lasts until the computer is shut down).

So if you want to permanently change the vBIOS rom that your GPU is using, you'd have to mod the BIOS.

**Comment by Th3Guardian** [comment]
You can flash with nvflash bro, I did it on an acer, but I was able to read the bios file from there, but the question is, would a write work? These guys are talking about a nvbios chip and that I would have to write on that instead. So seems like maybe the vcard does have a bioschip of its own? 
![image](https://user-images.githubusercontent.com/99751452/155229443-4717657f-4f83-42e3-8f15-25322d0024bc.png)

**Comment by Th3Guardian** [comment]
It's here man https://github.com/LaneLyng/MobilePascalTDPTweaker/releases

In any case, how would a flash to the main bios chip itself look like, provided I know how to put the modified rom into that bios file? And how do I even do that?

**Comment by T-vK** [comment]
Okay, I guess I'm wrong then. But there's a lot that doesn't make sense to me anymore now... 
I don't really know enough about nvflash etc to give you any meaningful advice, I have only used it to dump a vBIOS before, never to flash one. 
It does seem a bit risky though, since it would be a persistent flash. I'm not sure what's gonna happen if things go wrong.

Edit:
Flashing the main BIOS chip can be done with a hardware programmer.

Edit2: 
Something like this for example: https://www.ebay.com/itm/254978419809

On Linux, you simply use the `flashrom` command to read/write from the chip. On Windows you might be able to use `flashrom` too through wsl, but there are probably other more convenient tools for Windows.
You can find a bunch of guides on that topic online.

**Comment by T-vK** [comment]
Feel free to reopen.
